export const EMPLOYEES_ADD_REQUEST = 'EMPLOYEES_ADD_REQUEST';
export const EMPLOYEES_ADD_SUCCESS = 'EMPLOYEES_ADD_SUCCESS';
export const EMPLOYEES_ADD_FAIL = 'EMPLOYEES_ADD_FAIL';

export const EMPLOYEES_GET_REQUEST = 'EMPLOYEES_GET_REQUEST';
export const EMPLOYEES_GET_SUCCESS = 'EMPLOYEES_GET_SUCCESS';
export const EMPLOYEES_GET_FAIL = 'EMPLOYEES_GET_FAIL';

export const UPDATE_EMPLOYEE_REQUEST = 'UPDATE_EMPLOYEE_REQUEST';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const UPDATE_EMPLOYEE_FAIL = 'UPDATE_EMPLOYEE_FAIL';

export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_FAIL = 'DELETE_EMPLOYEE_FAIL';

export const FIND_EMPLOYEE_REQUEST = 'FIND_EMPLOYEE_REQUEST';
export const FIND_EMPLOYEE_SUCCESS = 'FIND_EMPLOYEE_SUCCESS';
export const FIND_EMPLOYEE_FAIL = 'FIND_EMPLOYEE_FAIL';
